pools:
  - name: home-pool
    addresses:
      - 192.168.0.60-192.168.0.99
  - name: pihole-pool
    addresses:
      - 192.168.0.50-192.168.0.59

advertisements:
  - name: home-l2
    ipAddressPools:
      - home-pool
  - name: pihole-l2
    ipAddressPools:
      - pihole-pool
