---
# Helmfile for home-cluster
# Manages Helm chart deployments across the cluster

repositories:
  - name: headlamp
    url: https://kubernetes-sigs.github.io/headlamp/
  - name: jetstack
    url: https://charts.jetstack.io
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/
  - name: metallb
    url: https://metallb.github.io/metallb

releases:
  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    version: 0.16.1
  - name: metallb-pool
    needs:
      - metallb
    namespace: metallb-system
    chart: ./charts/metallb-pool
    values:
      - ./values/metallb-pool.values.yaml
  - name: pihole-admin-secret
    namespace: pihole
    chart: ./charts/pihole-admin-secret
    values:
      - ./values/pihole-admin-secret.values.yaml
  - name: pihole
    needs:
      - pihole-admin-secret
    namespace: pihole
    chart: mojo2600/pihole
    version: 2.36.0
    values:
      - ./values/pihole.values.yaml
  - name: my-headlamp
    namespace: kube-system
    chart: headlamp/headlamp
    version: 0.41.0

    # needs:
    #   - cert-manager/cert-manager-issuers
    # values:
    #   - replicaCount: 2
    #     ingress:
    #       enabled: true
    #       ingressClassName: traefik
    #       hosts:
    #         - host: headlamp.192.168.0.109.sslip.io
    #           paths:
    #             - path: /
    #               type: ImplementationSpecific
