---
# Helmfile for home-cluster
# Manages Helm chart deployments across the cluster

environments:
  default:
    values:
      - rootDomain: home.arpa

---
repositories:
  - name: headlamp
    url: https://kubernetes-sigs.github.io/headlamp/
  - name: grafana-community
    url: https://grafana-community.github.io/helm-charts
  - name: jetstack
    url: https://charts.jetstack.io
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: mojo2600
    url: https://mojo2600.github.io/pihole-kubernetes/
  - name: metallb
    url: https://metallb.github.io/metallb
  - name : external-dns
    url: https://kubernetes-sigs.github.io/external-dns/
  - name: jetstack
    url: https://charts.jetstack.io
  - name: jameswynn
    url: https://jameswynn.github.io/helm-charts


releases:
  - name: metallb
    namespace: metallb-system
    chart: metallb/metallb
    version: 0.16.1
  - name: metallb-pool
    needs:
      - metallb
    namespace: metallb-system
    chart: ./charts/metallb-pool
    values:
      - ./values/metallb-pool.values.yaml
  - name: pihole-admin-secret
    namespace: pihole
    chart: ./manifests/pihole-admin-secret
  - name: pihole-admin-secret-kube-system
    namespace: kube-system
    chart: ./manifests/pihole-admin-secret
  - name: pihole
    needs:
      - pihole-admin-secret
    namespace: pihole
    chart: mojo2600/pihole
    version: 2.36.0
    values:
      - ./values/pihole.values.yaml
  - name: external-dns
    needs:
      - pihole-admin-secret-kube-system
    namespace: kube-system
    chart: external-dns/external-dns
    version: 1.21.1
    values:
      - ./values/external-dns.values.yaml
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: 1.20.2
    set:
      - name: installCRDs
        value: true
  - name: root-ca-bootstrap
    needs:
      - cert-manager
    namespace: cert-manager
    chart: ./charts/root-ca-bootstrap
    values:
      - ./values/root-ca-bootstrap.values.yaml.gotmpl
  - name: leaf-cert
    needs:
      - cert-manager/root-ca-bootstrap
    namespace: kube-system
    chart: ./charts/leaf-cert
    values:
      - ./values/leaf-cert.values.yaml.gotmpl
  - name: traefik-default-tls
    needs:
      - kube-system/leaf-cert
    namespace: kube-system
    chart: ./charts/traefik-default-tls
    values:
      - tlsStore:
          name: default
          namespace: kube-system
          secretName: default-tls-cert

# ---
# Could be separate helmfile

    # - name: my-headlamp
    #   namespace: kube-system
    #   chart: headlamp/headlamp
    #   version: 0.41.0

    # needs:
    #   - cert-manager/root-ca-bootstrap
    # values:
    #   - replicaCount: 2
    #     ingress:
    #       enabled: true
    #       ingressClassName: traefik
    #       hosts:
    #         - host: headlamp.192.168.0.109.sslip.io
    #           paths:
    #             - path: /
    #               type: ImplementationSpecific
  - name: home
    namespace: homepage
    createNamespace: true
    chart: jameswynn/homepage
    values:
      - ./values/homepage.values.yaml
  - name: ngnix-test
    namespace: default
    chart: ./manifests/ngnix-test
  - name: loki
    namespace: monitoring
    createNamespace: true
    chart: grafana-community/loki
    values:
      - ./values/loki.values.yaml
  - name: k8s-monitoring
    needs:
      - monitoring/loki
    namespace: monitoring
    chart: grafana/k8s-monitoring
    version: 4.1.6
    values:
      - ./values/k8s-monitoring.values.yaml
  - name: kps
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: 87.0.0
    values:
      - ./values/prometheus.values.yaml
