apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.certificate.namespace }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  isCA: true
  subject:
    organizations:
{{ toYaml .Values.certificate.subject.organizations | indent 6 }}
    organizationalUnits:
{{ toYaml .Values.certificate.subject.organizationalUnits | indent 6 }}
    countries:
{{ toYaml .Values.certificate.subject.countries | indent 6 }}
    provinces:
{{ toYaml .Values.certificate.subject.provinces | indent 6 }}
    localities:
{{ toYaml .Values.certificate.subject.localities | indent 6 }}
  commonName: {{ .Values.certificate.commonName | quote }}
  dnsNames:
{{ toYaml .Values.certificate.dnsNames | indent 4 }}
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
---
# Traefik will use this TLSStore to serve the default certificate for any TLS request that doesn't match a specific TLSRoute
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: {{ .Values.certificate.namespace }}
spec:
  defaultCertificate:
    secretName: {{ .Values.certificate.secretName }}
