{{- range .Values.pools }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .name }}
spec:
  addresses:
{{- range .addresses }}
    - {{ . | quote }}
{{- end }}
---
{{- end }}
{{- range .Values.advertisements }}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .name }}
spec:
  ipAddressPools:
{{- range .ipAddressPools }}
    - {{ . }}
{{- end }}
---
{{- end }}
