apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: {{ .Values.certificate.namespace }}
spec:
  defaultCertificate:
    secretName: {{ .Values.certificate.secretName }}
